apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: eclipse-che-preview-openshift
  namespace: openshift-marketplace
spec:
  authorizationToken: {}
  endpoint: 'https://quay.io/cnr'
  registryNamespace: dfestal-tests
  type: appregistry
